### PR TITLE
Helium

### PR DESCRIPTION
**Pull request by DivineEnergylol**
added helium src released by shotbowxd the owner of helium

### CODE REVIEW

**Comment by chocopie69** [comment]
no

**Comment by Shotbowxd** [comment]
> no

add it now or i will eat you

**Comment by chocopie69** [comment]
> add it now or i will eat you

you're mom

**Comment by Shotbowxd** [comment]
> > add it now or i will eat you
> 
> you're mom

Yeah ok buddy now I won’t eat you

**Pull request merged**
